version: "3"
services:
  api:
    build:
      context: .
      dockerfile: dockerfile
    image: alihmaidi/asp_ecommerce
    ports:
      - "8000:80"
    depends_on:
      - redis
    
    networks:
     - redis
  redis:
    image: redis
    ports:
      - "6379:6379"
      
    networks:
     - redis      
networks:
  redis:
    driver: bridge