version: "3"
services:
  api:
    build:
      context: .
      dockerfile: dockerfile
    image: alihmaidi/asp_ecommerce
    ports:
      - "8000:80"
    depends_on:
      - redis
  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/nginx.conf
    depends_on:
      api:
        condition: service_started
        restart: true
      
      redis:
        condition: service_started
        restart: true
      
  
  redis:
    image: redis
    ports:
      - "6379:6379"