version: "3"
services:
  api:
    build:
      context: .
      dockerfile: dockerfile
    image: alihmaidi/asp_ecommerce
    ports:
      - "8000:80"
  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/nginx.conf
    depends_on:
      - api
