apiVersion: v1
kind: Service
metadata:
  name: database-service-access

spec:
  type: LoadBalancer
  selector:
    app: mssql
  ports:
  - port: 1444
    name: mssql
    protocol: TCP
    targetPort: 1433

