apiVersion: v1
kind: Service

metadata:
  name: authneticationservice
spec:
  type: LoadBalancer
  selector:
    app: authentication
  ports:
  - name: authenticationservice
    port: 8070
    targetPort: 80

