apiVersion: apps/v1
kind: Deployment

metadata:
  name: authentication

spec:

  replicas: 1
  selector:
    matchLabels:
      app: authentication
  template:
    metadata:
      labels:
        app: authentication
    spec:
      containers:
      - name: authenticationservice
        image: alihmaidi/asp_ecommerce

